### ISSUE TITLE
SaySounds

### ISSUE THREAD

**Issue by Rebellsko** [oqyh/cs2-MVP-Sounds-GoldKingZ#4]
Hello, 
 
i really like your plugins - good work.
No issue but a question: can you build something like "SaySounds" LINK: https://forums.alliedmods.net/showthread.php?p=2240969

Thanks anyway !!

**Comment by oqyh** [comment]
> Hello,
> 
> i really like your plugins - good work. No issue but a question: can you build something like "SaySounds" LINK: https://forums.alliedmods.net/showthread.php?p=2240969
> 
> Thanks anyway !!

hello 🙋‍♂️ 
glade u like it
we are working on it, thats will be saparte plugin 
we need 3d audio that trigger from player him self
rather than everyone hear it direct without player location who say/play the sound
